### ISSUE TITLE
Language is not correct when session timed out

### ISSUE THREAD

**Issue by frederikprijck** [SondagesPro/LimeSurvey-SondagesPro#1]
When you start the survey and select GERMAN language, then delete the PHPSession Cookie and click NEXT, the session time out page is displayed in english.

**Comment by Shnoulle** [comment]
Fixed in https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/8fc152da69f1a272382fcd238d495b802c310478

and new feature in https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/8449b2210075e173d5d4d60925fcc6ba3fa62a54
