### ISSUE TITLE
PHP error when using KCfinder in L.S. SondagesPro 1.7.1

### ISSUE THREAD

**Issue by fvanderstarre** [SondagesPro/LimeSurvey-SondagesPro#11]
When trying to insert an image file into question text, after clicking "Browse server" in KCfinder, an error is displayed:
"Internal Server Error
Undefined index: config"
Server log says: PHP Notice:  Undefined index: config in /data/websites/limesurvey-test/html/cru/application/core/LSYii_Application.php on line 47
PHP version is 5.6.40.
Works OK in PHP 7.2.18.

**Comment by Shnoulle** [comment]
Surely related to https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/0cd6c1d9e716de621d4946efeaa39fa3e56d5f54

**Comment by Shnoulle** [comment]
I can't reproduce … with debug=2 and PHP Version 5.6.40 …

User config is read here : https://github.com/SondagesPro/LimeSurvey-SondagesPro/blob/0cd6c1d9e716de621d4946efeaa39fa3e56d5f54/application/core/LSYii_Application.php#L46

Check your config.php file, maybe an outdated version …

**Comment by fvanderstarre** [comment]
You're right, there was an error in my config.php file. :-(
Sorry to bother you!
