### ISSUE TITLE
Fix for multilingual group and question import (MS-SQL)

### ISSUE THREAD

**Issue by fvanderstarre** [SondagesPro/LimeSurvey-SondagesPro#12]
Hi Denis,
I was unable to fork and make a pull request for 2.6.7 SondagesPro - but here are some fixes for application/helpers/admin/import_helper.php and /application/helpers/export_helper.php.
import_helper: multilingual group or question import fixed for MS-SQL (marked 'FvdS')
export_helper: some query adaptations for PHP 7 / MS-SQL (also marked 'FvdS')
Best regards,
Frank

[import-export helpers.zip](https://github.com/SondagesPro/LimeSurvey-SondagesPro/files/3496348/import-export.helpers.zip)

**Comment by Shnoulle** [comment]
Maybe it's due to already existing fork : https://github.com/fvanderstarre/LimeSurvey

Maybe you can add it at second remote repository in https://github.com/fvanderstarre/LimeSurvey ?

**Comment by Shnoulle** [comment]
Already in https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/0bdbbf15ed1fa8e0e3978c90d911da09b807880c

Right ?

**Comment by fvanderstarre** [comment]
I’m not sure!
Can you merge? I had some trouble with the pull requests…

Thx!
Frank van der Starre

[cid:image001.png@01D40E30.9B2FFEE0]
Frank van der Starre  |  Applicatiebeheerder
Dienst ICT – Applicatiemanagement – Koppelingen en Systeemontwikkeling
Locatie AMC | Kamernummer HA1.35 | Tafelbergweg 51 | 1105 BD Amsterdam
T: 020-5664101  |  E: f.l.vanderstarre@amsterdamumc.nl
Afwezig: woensdag, en even weken ook maandag
www.amsterdamumc.nl<http://www.amsterdamumc.nl/> | www.amc.nl<http://www.amc.nl/>

Van: Denis Chenu <notifications@github.com>
Verzonden: vrijdag 11 oktober 2019 10:17
Aan: SondagesPro/LimeSurvey-SondagesPro <LimeSurvey-SondagesPro@noreply.github.com>
CC: Starre, F.L. van der (Frank) <f.l.vanderstarre@amsterdamumc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [SondagesPro/LimeSurvey-SondagesPro] Fix for multilingual group and question import (MS-SQL) (#12)


Already in 0bdbbf1<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSondagesPro%2FLimeSurvey-SondagesPro%2Fcommit%2F0bdbbf15ed1fa8e0e3978c90d911da09b807880c&data=02%7C01%7Cf.l.vanderstarre%40amsterdamumc.nl%7Cdc4fa209c917492a67a908d74e236083%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C637063786162033805&sdata=EQTnEVhOJbYo9yGU5NfW8ySmCI%2Fzb8glvg%2FqpEwWKi0%3D&reserved=0>

Right ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSondagesPro%2FLimeSurvey-SondagesPro%2Fissues%2F12%3Femail_source%3Dnotifications%26email_token%3DAIFGEZMO7EA2YPSPBWPKFL3QOAY6ZA5CNFSM4ILJABQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7HOWQ%23issuecomment-540964698&data=02%7C01%7Cf.l.vanderstarre%40amsterdamumc.nl%7Cdc4fa209c917492a67a908d74e236083%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C637063786162033805&sdata=n%2FzUPKYM%2BhAFt0CMhwh5kg869m8okpWpw6Q7ge6dC2Q%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIFGEZJT4JLN4PJTCTC2LOTQOAY6ZANCNFSM4ILJABQQ&data=02%7C01%7Cf.l.vanderstarre%40amsterdamumc.nl%7Cdc4fa209c917492a67a908d74e236083%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C637063786162043761&sdata=6zCpr6YyvEPQrzebemssBDVxakcvCBTmFzJCAEfBEd4%3D&reserved=0>.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/SondagesPro/LimeSurvey-SondagesPro/issues/12?email_source=notifications\u0026email_token=AIFGEZMO7EA2YPSPBWPKFL3QOAY6ZA5CNFSM4ILJABQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7HOWQ#issuecomment-540964698", "url": "https://github.com/SondagesPro/LimeSurvey-SondagesPro/issues/12?email_source=notifications\u0026email_token=AIFGEZMO7EA2YPSPBWPKFL3QOAY6ZA5CNFSM4ILJABQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7HOWQ#issuecomment-540964698", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
______________________________________________________
VUmc disclaimer : www.vumc.nl/disclaimer
AMC disclaimer : www.amc.nl/disclaimer

**Comment by Shnoulle** [comment]
I can not merge : same line updated in master.
