### ISSUE TITLE
Error in map question with OSM

### ISSUE THREAD

**Issue by Shnoulle** [SondagesPro/LimeSurvey-SondagesPro#2]
See https://bugs.limesurvey.org/view.php?id=11455

**Comment by Shnoulle** [comment]
https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/a141dedc6a4447365f1b1200515dc8d12b840f8b

**Comment by LouisGac** [comment]
maybe we should port it to 2.06lts?

**Comment by Shnoulle** [comment]
I make a feature request for https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/a141dedc6a4447365f1b1200515dc8d12b840f8b#diff-a9dbc6157f3066d12e04af89a4bca062L3018 (show all world and not only Germany part for OSM and a sea for GMap :) 

After : porting to 2.06lts : do it if you want :)

**Comment by LouisGac** [comment]
isn't that branch a fork of 2.06lts?

**Comment by Shnoulle** [comment]
Yes, with some other feature (lot of event in fact ), lts is feature fixed. And i update some 'not discussed' system : for example ANSWERTABLE is awfull today, must be improved. I just improved it quickly but need more work to be better.

**Comment by LouisGac** [comment]
ok, I understand why you can't just PR that commit. 
and, also, less and less people use 2.06. The only obligation we have is to port the security fixes to LTS.

**Comment by Shnoulle** [comment]
I'm OK for the lts : really no issue here :) but this patch is very little and the question is broken without ;). It's just why i put the information on the commit of master branch.
