### ISSUE TITLE
Mandatory date/time question does not work without date.

### ISSUE THREAD

**Issue by SamMousa** [SondagesPro/LimeSurvey-SondagesPro#3]
When using an input mask of `HH:MM` or `HHMM` the interface is shown correctly (it shows a picker without date) but question validation fails and you get a `this question is mandatory` popup.

**Comment by Shnoulle** [comment]
2.06lts have this issue too ?

**Comment by SamMousa** [comment]
Yes.

**Comment by Shnoulle** [comment]
I think there are same issue with month only (or day)

**Comment by SamMousa** [comment]
Could be related to MySQL not allowing invalid dates (0000-00-00) since 5.7.

**Comment by Shnoulle** [comment]
No it was before trying to save in DB (with THIS version) because : https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/029ec41c535256785a84b0c9eb578e45f857da52

But we surely validate date somewhere in em_manager_helper.php

**Comment by Shnoulle** [comment]
Fixed in https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/e3f01b28a39f633a9b49723abf8eff5dc5fd6897
