### ISSUE TITLE
Illegal string offset 'Position' - show statistics

### ISSUE THREAD

**Issue by fvanderstarre** [SondagesPro/LimeSurvey-SondagesPro#9]
Show statistics: PHP warning : Illegal string offset 'Position'.

[PHP warning.txt](https://github.com/SondagesPro/LimeSurvey-SondagesPro/files/2996131/PHP.warning.txt)

Using Version 2.6.7 Build SondagesPro 1.6.6, PHP 7.2.14, RHEL 7, MS-SQL (pdo dblib, FreeTDS).

**Comment by Shnoulle** [comment]
Arg php7 and pchart …

**Comment by Shnoulle** [comment]
can you send a simple LSA to try to reproduce the issue .

**Comment by Shnoulle** [comment]
Fixed in https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/36a821ca54e87715d4ab53b4bbe8616a2bcbdce6
If it still happen : test with limesurvey master
